name: places
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.0.3
  provider: ^6.0.3

  substring_highlight: ^1.0.33

  dio: ^4.0.6

  intl: ^0.17.0

  _fe_analyzer_shared: ^39.0.0
  async: ^2.8.2


  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  formz: ^0.4.1

  rxdart: ^0.27.4

  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^4.15.1
  analyzer: ^4.0.0

  build_runner: ^2.1.10

flutter:
  assets:
    - assets/icons/
    - assets/icons/delete.svg
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Roboto-Black
      fonts:
        - asset: assets/res/fonts/Roboto-Black.ttf
    - family: Roboto-BlackItalic
      fonts:
        - asset: assets/res/fonts/Roboto-BlackItalic.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/res/fonts/Roboto-Bold.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/res/fonts/Roboto-BoldItalic.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/res/fonts/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/res/fonts/Roboto-Light.ttf
    - family: Roboto-LightItalic
      fonts:
        - asset: assets/res/fonts/Roboto-LightItalic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/res/fonts/Roboto-Medium.ttf
    - family: Roboto-MediumItalic
      fonts:
        - asset: assets/res/fonts/Roboto-MediumItalic.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/res/fonts/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/res/fonts/Roboto-Thin.ttf
    - family: Roboto-ThinItalic
      fonts:
        - asset: assets/res/fonts/Roboto-ThinItalic.ttf
